name: timelines
version: 0.0.2
description: A powerful & easy to use timeline package for Flutter. All UI components in this package are separate widgets.
homepage: https://chulwoo.dev
repository: https://github.com/chulwoo-park/timelines/
issue_tracker: https://github.com/chulwoo-park/timelines/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter: 
