name: timelines
version: 0.0.1
description: Widgets that make it easy to implement the timeline UI component.
homepage: https://chulwoo.dev
repository: https://github.com/chulwoo-park/timelines/
issue_tracker: https://github.com/chulwoo-park/timelines/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
